### PR TITLE
Fix bugs

### LINKED ISSUE #16: The home page is not working properly
**Describe the bug**
The home page is not working properly as before 

**To Reproduce**
1. Go to https://vishwaamarasinghe.github.io/codeflow-website/

**Expected behavior**
Remove unwanted things and fix te bugs 

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by VishwaAmarasinghe**
## Purpose

To fix #16 
  
## Describe 
 
  This pr is fixing bugs

## Order

- 1 Doing changes to it

## Screenshot

image

  
## Preview-link

  https://vishwaamarasinghe.github.io/codeflow-website/

## Check-list
- [x] This pr is self-reviwed by you before commiting.
- [x] This pr is not damaging to this website.
- [x] This pr is protecting the privacy.

### CODE REVIEW

**Comment by VishwaAmarasinghe** [comment]
Done!

**Comment by daniduthisum** [comment]
Nice..!

**Comment by daniduthisum** [comment]
Can you merge this.

**Comment by VishwaAmarasinghe** [comment]
yeah sure

**Comment by daniduthisum** [comment]
Shall i work on this

**Pull request merged**
