### PR TITLE
Add navbar and Footer

### LINKED ISSUE #2: Add navbar and footer
**Is your feature request related to a problem? Please describe.**
We should add a navbar and footer first beacause it will easy to go ahead.

**Describe the solution you'd like**
Add a some html and bootstrap tag with css

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by VishwaAmarasinghe**
## Purpose

To fix #2 
  
## Describe 
 
  This pr is  adding the navbar and footer to website

## Order

- 1 To navbar look at bootstrap and get the code.
- 2 Remove unwanted commands and add what we need.
- 3 Add some CSS to the navbar to get a perfect navbar.
- 4 To footer add footer tag.
- 5 Add hr tag and add college name with social media icons

## Screenshot

image
image

  
## Preview-link

 https://vishwaamarasinghe.github.io/codeflow-website/
  
## Check-list
- [x] This pr is self-reviwed by you before commiting.
- [x] This pr is not damaging to this website.
- [x] This pr is protecting the privacy.

### CODE REVIEW

**Comment by daniduthisum** [comment]
Correct the logo and update the screenshot

**Comment by VishwaAmarasinghe** [comment]
> Correct the logo and update the screenshot

Working on it..

**Comment by VishwaAmarasinghe** [comment]
Working on footer .

**Comment by daniduthisum** [comment]
Looking perfect to me.Please merge

**Pull request merged**
